name: Context
on:
  issues: 
    types: [opened]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Prints the issue details
        run: echo ${{ toJSON(env.ISSUE) }}
    env:
      ISSUE: ${{github.event.issue}}
